### ISSUE TITLE
Fork the project as hexcurse-ng and add a proper release cycle

### ISSUE THREAD

**Issue by MIvanchev** [prso/hexcurse#6]
Hi! Long term user of hexcurse here, I recently decided to suggest adding hexcurse to Void Linux (see [here](https://github.com/void-linux/void-packages/pull/51501)) but it was reject on the grounds that the project is now most likely dead. Since it looks that way to me too and you're already doing hell of a job supporting it I suggest forking it as hexcurse-ng or something and continuing the work there in a more official manner along with a proper release cycle. I'm ready to help out. Hexcurse is just to good to fall into obscurity.

**Comment by prso** [comment]
Ok, project renamed and made standalone to improve visibility.

Next step: make a release. The last version was 1.60 so I think a new version number could be 1.70 to reflect all the changes.

**Comment by MIvanchev** [comment]
Yes good idea, definitely a release and I'll also PR you some text explaining how we got here.

**Comment by prso** [comment]
**[v1.70.0 released](https://github.com/prso/hexcurse-ng/releases/tag/v1.70.0)!**

**Comment by MIvanchev** [comment]
Epic, thank you so muh, hexcurse really deserves it and you've been taking care of it well!!
